version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "11:00"
  assignees:
    - "jawnsy"
  reviewers:
    - "jawnsy"
  ignore:
    # GitHub always delivers the latest versions for each major
    # release tag, so ignore minor version tags
    - dependency-name: "actions/cache"
      versions:
        - 2.x
    - dependency-name: "actions/checkout"
      versions:
        - 2.x

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
    time: "11:00"
  assignees:
    - "jawnsy"
  reviewers:
    - "jawnsy"
