blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/cdr/code-server/discussions/new?category_id=22503114
    about: Ask the community for help on our GitHub Discussions board
  - name: Need immediate help or just want to talk?
    about: Hop in our Slack and talk to the code-server engineers and community
    url: https://cdr.co/join-community
